### ISSUE TITLE
[BUG] On shortcut execution android switches to home screen where app icon is

### ISSUE THREAD

**Issue by eleksis** [Waboodoo/HTTP-Shortcuts#203] opened 2020-11-02 14:49 UTC
**Steps To Reproduce**
If i have shortcut icon on main home screen and icon of the app on "secondary" home screen. Android jumps to secondary screen (where original app is) every time i execute shortcut. I suspect it has something to do with response handling. But setting it to 'run silently' does not help. Not sure if this is app or os related.

**Expected behavior**
Should not switch to other home screen.

**Context (please complete the following information):**
 - Android OS Version: 10
 - App Version 1.38.0

**Comment by Waboodoo** [comment] 2020-12-12 15:24
Hello,
I was not able to reproduce this issue, but I have received reports from other users about this as well. This behavior is outside of the control of the app, and I suspect it is entirely up to the OS or the launcher used. As such, most likely there is nothing I can do about this.

**Comment by eleksis** [comment] 2020-12-13 17:30
Thanks for reply.

If someone else comes across this issue. I have created "group/folder" on main home screen and put HTTP-shortcuts icon in there (with other apps not used regularly). Now both my custom shortcut icon and HTTP-shortcuts app are on the same scrren, which sort of fixes original problem.

**Comment by Waboodoo** [comment] 2023-08-25 08:07
Doing a bit of cleanup here. I'm closing this issue now because there's nothing I can do about it from the app's side. The reported behavior is governed by the launcher.

**Closed by Waboodoo** 2023-08-25 08:07 UTC
Labels: bug
