### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by xmha97** [Waboodoo/HTTP-Shortcuts#310] opened 2022-11-19 13:04 UTC
Please use an adaptive icon.

**Comment by Waboodoo** [comment] 2022-11-20 11:11
The app already uses an adaptive icon.

**Comment by xmha97** [comment] 2022-11-20 12:39
Please reopen this issue.
On Xiaomi phones, there is no animation when the icon of this app moves.

Please reopen this issue.

**Comment by xmha97** [comment] 2022-11-20 12:42
https://user-images.githubusercontent.com/23485114/202902469-82338413-29d9-407f-b66d-4a040baf55c5.mp4

**Comment by xmha97** [comment] 2022-11-20 12:44
@Waboodoo Please reopen this issue.

**Comment by Waboodoo** [comment] 2022-11-20 13:46
Interesting... I cannot reproduce this on any of my devices, so I suspect this is specific to Xiaomi. I have an idea what might be the cause, but as I can't test it I can't guarantee that that will fix it.

**Comment by xmha97** [comment] 2022-11-20 14:13
https://github.com/mueller-ma/Coffee
This problem does not exist in this app, please see its codes.

**Comment by xmha97** [comment] 2022-11-27 21:51
@Waboodoo 
When will the new version be released?

**Comment by Waboodoo** [comment] 2022-11-27 23:04
I don't know yet. I still have some other bugs I need to look into that I want to have fixed in the next release. If I find the time I might be able to release within the next week, but it might also take longer.

**Comment by xmha97** [comment] 2022-11-28 05:34
OK, thanks for your reply.

**Comment by Waboodoo** [comment] 2022-12-01 06:53
Version 2.26.0 is now available for beta testing, which includes the fix for this issue, assuming that it actually fixes it. You can join the beta program here: https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts

**Comment by xmha97** [comment] 2022-12-01 09:07
Thank you, but the issue is not fixed:

https://user-images.githubusercontent.com/23485114/205011490-aeea1530-1702-427c-8ddc-1e67b9d026ca.mp4

**Comment by Waboodoo** [comment] 2022-12-01 09:40
Unfortunately, then I really don't know how to fix this. It works on my test devices, and I don't see what I'm doing wrong.

**Comment by xmha97** [comment] 2022-12-01 10:06
This problem is not in any of the apps that I installed, for example:
https://github.com/mueller-ma/Coffee
If you release debug builds, I'll test them.

**Comment by Waboodoo** [comment] 2022-12-01 12:56
I honestly don't know what is different in my app. I made some more small tweaks, here's an APK build for it that you can try:
https://http-shortcuts.rmy.ch/files/app-universal-release.apk

If that does not solve the issue then I'm giving up, as I don't want to spend this much time on something so minor.

**Comment by xmha97** [comment] 2022-12-01 16:26
Thanks for this build, but unfortunately the problem is not solved, if you want, close this issue.

**Comment by Waboodoo** [comment] 2022-12-01 19:53
Ok, shame, I'm out of ideas. I will close this as Won't Fix then and assume that this is another case of Xiaomi doing weird things.

**Closed by Waboodoo** 2022-12-01 19:53 UTC
Labels: bug, release soon

**Comment by Jesse205** [comment] 2023-08-18 11:36
![Screenshot_20230818_193426_com.huawei.android.launcher.jpg](https://github.com/Waboodoo/HTTP-Shortcuts/assets/51242302/899647b0-2407-4856-92ca-d2eb661a689a)
Abnormal display of desktop icons on Huawei devices.

Because the software placed the icon under drawable instead of mipmap anydpi v26
![Screenshot_20230818_193327.jpg](https://github.com/Waboodoo/HTTP-Shortcuts/assets/51242302/84a3ed37-6cf9-4e8b-8d31-add672c79d56)

The correct approach is to use Android Studio to generate icons, and Studio will place them in the correct location.

**Comment by Waboodoo** [comment] 2023-08-19 10:51
The `ic_launcher.xml` file is already placed inside `mipmap-anydpi-v26`. It's just the foreground drawable that's in the `drawable` directory, but it has to be there as it is a vector drawable and thus cannot be moved to the mipmap directory.
