### ISSUE TITLE
[BUG] Executing a shortcut and PiP (Picture in Picture)

### ISSUE THREAD

**Issue by haitham506** [Waboodoo/HTTP-Shortcuts#332] opened 2023-02-16 12:29 UTC
Hi,

Executing a shortcut from the (Quick Settings Tile) Triggers PiP (Picture in Picture) in the Opened App. 

Is it possible to add an option to not Trigger PiP on other Apps when exceuting a shotcut?

**Comment by Waboodoo** [comment] 2023-02-16 18:23
I am not able to reproduce this, and I'm also not really sure I understand the issue. Could you perhaps post some screenshots or a screen recording?

**Comment by Waboodoo** [comment] 2023-02-17 14:43
I see. I don't think I have any control over this. This is likely a behavior defined either by the Android system itself or by the PiP app.
Basically, whenever you trigger a shortcut (no matter how), it will very briefly open the HTTP Shortcuts app and close it again immediately. This means that Android or another app might decide to put the currently active window into PiP mode (if it supports it).

I can see a potential workaround that I could try implementing, but it would only work for very simple shortcuts, i.e., they couldn't use any of these features:
- file uploads
- Dynamic variables (i.e., variables other than static ones)
- Scripting
- any form of user interaction, such as asking for confirmation

Would that be the case for your shortcut(s) that you want to trigger through the Quick Settings Tile?

**Comment by Waboodoo** [comment] 2023-02-21 18:50
I hope it will. I'll have to experiment with this a bit. Can't make any promises when and if I'll be able to add this.

**Comment by Waboodoo** [comment] 2023-03-14 20:17
I have implemented a potential fix for this issue in version 2.31.0, which is now available on the beta channel. @haitham506 If you want to give it a try, you can join the [beta program](https://play.google.com/apps/testing/ch.rmy.android.http_shortcuts).

**Comment by Waboodoo** [comment] 2023-03-16 09:33
Glad to hear it works now. Yes, the rules for this are very restrictive, your shortcut has to be super simple and the conditions must be "perfect" (e.g., no battery saver or data saver on) for it to work.

If you do need some kind of visual feedback that the shortcut was triggered, you can change the response type to "Toast Popup", and then grant the app permission to display Notifications (which you'll have to do via the system settings, the app itself currently has no UI for this).

**Closed** 2023-03-17 15:33 UTC
Labels: bug, release soon

**Comment by Waboodoo** [comment] 2023-06-13 17:53
Could you elaborate what you mean by "this"? I'm struggling to reproduce an issue. I found one bug related to the quick settings tile, but it would only happen if the shortcut was configured to ask for confirmation before running. Is that perhaps the case for your shortcut?

**Comment by Waboodoo** [comment] 2023-07-14 14:04
@haitham506 Does the issue still exist in version 3.1.0? I had to do a bit of a hacky workaround, to get this to work. As a result, the picker dialog for selecting the shortcut to run might not be nicely styled, but it should work.
