### ISSUE TITLE
Array parameter

### ISSUE THREAD

**Issue by afk-mcz** [Waboodoo/HTTP-Shortcuts#77] opened 2017-09-11 13:41 UTC
Could you add support for array string parameter?

**Comment by Waboodoo** [comment] 2017-09-11 13:59
Could you elaborate on that? I'm not entirely sure what you mean, or what your use-case is.

**Comment by Arlefreak** [comment] 2017-09-11 14:55
I have an end point which the body looks like this

```
{
    "tags": ["foo", "bar"],
    "name": "name"
}
```

It would be nice if you can have an array field for the tags parameter.

**Comment by Waboodoo** [comment] 2017-09-17 13:14
This looks like a JSON body. To send a JSON body you need to specify a custom header "Content-Type" with the value "application/json" and then place your JSON body into the request body text field.

**Comment by Waboodoo** [comment] 2018-01-09 21:14
I'm closing this with the assumption that the issue is resolved or no longer relevant. Feel free to re-open if I'm wrong.

**Closed by Waboodoo** 2018-01-09 21:14 UTC
