### ISSUE TITLE
TriggerShortcut doesn't work when launching from homescreen widget

### ISSUE THREAD

**Issue by penbob3** [Waboodoo/HTTP-Shortcuts#175] opened 2020-05-08 02:19 UTC
I don't believe it's a background app sleep problem or anything, as the first shortcut executes perfectly fine, but the second does not. If I have two separate widgets and execute one after the other, it works and the variables are saved. I'm on Miui 11 - Android 10 on a Xiaomi CC9. How could I debug this?

**Comment by Waboodoo** [comment] 2020-05-09 08:22
Does it work when triggering the shortcut from within the app?

**Comment by penbob3** [comment] 2020-05-09 13:09
Yeah, it works in the app so the second routine name is definitely correct and triggers properly.

**Comment by Waboodoo** [comment] 2020-05-16 12:51
There's a number of factors that could play into this, so this is a big tricky to debug. Can you try:
- make sure that the 2nd shortcut does not use a delay
- change the "Response Type" in the "Response Handling" section of your first shortcut to "Response in Dialog" or "Response in Window"
- disable battery saver and data saver mode or exclude the app from them

**Comment by Waboodoo** [comment] 2020-08-16 10:24
There is now a trouble shooting option "Run Requests in Foreground" which you can enable in the app's Settings. Enabling it should solve your problem.

**Comment by xiozf** [comment] 2020-10-03 08:20
I have the same problem.

shortcutA:
const examples = new Date();
showToast(examples);

shortcutB:
const time = showSelection({
    'gettime': 'What is the time?',
    'nope': 'Cancel',
});
if (time == 'gettime') {
    triggerShortcut("shortcutA");
} else {
    showDialog('Nothing happened.', 'You canceled');
}

ShortcutB is placed on the home screen.Click ShortcutB and select the first option. ShortcutA is not running.Select the second option is no problem.
"Run Requests in Foreground" This option is enabled.

**Comment by Waboodoo** [comment] 2020-10-16 15:57
So far I was not able to reproduce this issue. I suspect it might a problem that only surfaces on Miui. I have an idea what the root cause might be, but fixing it will require larger changes to the app, so unfortunately this will have to wait a bit.

**Comment by tomillie** [comment] 2022-05-08 18:28
I was having the same issue on Android 11 and MIUI 12.5.4 and was able to fix it by enabling the **Display pop-up windows while running in the background** permission (available in Settings -> Apps -> Manage apps -> HTTP Shortcuts -> Other permissions) and renaming the `triggerShortcut()` method to `enqueueShortcut()`.

**Comment by Waboodoo** [comment] 2022-05-09 17:43
@tomillie Thanks for this valuable piece of insight. This seems to indeed be a common issue with apps running on Xiaomi devices. I will add a button to the troubleshooting section of the app to more easily find this permission screen, hopefully that will help.

Renaming `triggerShortcut()` to `enqueueShortcut()` shouldn't make a difference here though. The two are equivalent, as one is just an alias for the other.

**Comment by Waboodoo** [comment] 2022-05-14 10:59
Given that this seems to be a bug (or "unfortunate feature") in MIUI and not the app, and that there is a workaround advertised in the app, I'm now closing this issue as there's probably nothing I can further do to fix this.

**Closed by Waboodoo** 2022-05-14 10:59 UTC
Labels: bug, release soon
