### ISSUE TITLE
Feature Request: Warn about overwriting Data when importing backups

### ISSUE THREAD

**Issue by aslmx** [Waboodoo/HTTP-Shortcuts#120] opened 2019-01-28 21:07 UTC
I just imported some shortcuts i had created on another Phone.

I had already a bad feeling so i exported my new shortcuts before. Boy was i lucky to have done this...

After importing the old data my new shortcuts were gone :-O

Please add at least a warning.

Better: why overwrite something at all? Don't delete before importing... Just merge stuff and only overwrite if shortcuts have same name or so... 

Thanks for consideration!

... and now i'll merge the two exports into one file, so i can import old and new data...

**Comment by aslmx** [comment] 2019-01-28 21:15
We'll pardon me... i had not seen the tiny little warning that "existing shortcuts MIGHT be overwritten" ;-)

sorry.

Still i ask you to improve on this. The warning should be clearer or not be necessary at all...

**Comment by Waboodoo** [comment] 2019-02-02 12:32
I see your problem, and thank you for reporting this.

The merging logic is mainly a technical limitation of how the app had been built from the very start. Each shortcut has an id, and when importing shortcuts they are matched by that id, i.e., a shortcut from the import that has the same id as one that already exists will override that one. The problem is that these ids are just incrementing integers, so it can happen very easily that there would be an id match even though they are different shortcuts otherwise.

I'll see how I can fix this.

**Comment by aslmx** [comment] 2019-02-04 20:32
I was able to manually merge the two exports, but it was a PITA 😉

Would be nice if you could improve this. Thanks!

**Comment by Waboodoo** [comment] 2019-03-24 09:26
This is now improved in version 1.24 (expected to be released in about 2 weeks). Shortcut IDs are now UUIDs instead of integers, making it (virtually) impossible for an imported shortcut to overwrite an existing one, unless they really are the same shortcut.

**Closed by Waboodoo** 2019-03-24 09:26 UTC
