### ISSUE TITLE
Delay for executing shortcut by shortcut

### ISSUE THREAD

**Issue by exw777** [Waboodoo/HTTP-Shortcuts#145] opened 2019-08-31 20:50 UTC
![Screenshot_20190831_234749](https://user-images.githubusercontent.com/46466764/64069011-c9b0d900-cc49-11e9-8d6a-1a6e8c0ae8a9.jpg)
![Screenshot_20190831_234950](https://user-images.githubusercontent.com/46466764/64069030-0c72b100-cc4a-11e9-82e0-477ba87946bc.jpg)
Default time to execute is about 5sec?! How to change it?

**Comment by Waboodoo** [comment] 2019-09-01 09:45
There is a delay of 500 milliseconds when a shortcut is triggered from another shortcut. However, that delay only starts once the current shortcut is fully executed, including any Success actions. For example if your current shortcut displays the response in a dialog, the other shortcut is not triggered until you dismiss that dialog.

Can you give some more details about your use-case, so I can see if it can be facilitated somehow?

**Comment by exw777** [comment] 2019-09-01 20:11
Example video where shortcut 1 execute shortcut 2 with delay 5sec
[https://cloud.mail.ru/public/KFoX/oVVNmWqnX](url)

**Comment by Waboodoo** [comment] 2019-09-15 09:30
I cannot reproduce this issue, and the link you posted returns a 404.

This may also be a limitation of the Android OS itself, or of settings around Battery Saver or Data Saver modes.

**Comment by Waboodoo** [comment] 2020-04-13 15:16
This issue should be fixed in version 1.29.0, which will be released soon.

**Closed** 2020-05-03 17:05 UTC
