### ISSUE TITLE
[BUG]  biometric facial recogntion in low light exceeds retry count

### ISSUE THREAD

**Issue by snowdej** [Waboodoo/HTTP-Shortcuts#391] opened 2023-10-28 15:41 UTC
### Steps To Reproduce
use biometric authentication
user biometric with facial recognition on pixel 8 (pixel 8 facial is ok for banking apps no fingerprint)
use in dark light that on other apps asks for fingerprrint

### Expected behavior
shows fingerprint toast
allows fingerprint to confirm

### Actual behavior
it says failed (it does not show fingerprint) 
it says you've tried too many times
to get it to work again I had to change to simple confirmation and back to biometric

### Context
Please complete the following information:
- android 14
- 3.6.0 beta

I would like to be able to choose biometric or biometric fingerprint .  So that I can always demand a fingerprint even if facial recognition is actually available.  As in force use of a fingerprint and ignore facial recog.  This is also partly  a change request to fix the problem .  I dont really want to use facial recog as I use the fingerprint as a confirmation - which means when facial recog is on hitting the shortcut just executes as it sees your face.

**Comment by Waboodoo** [comment] 2023-11-18 18:31
To my understanding, this is unfortunately not possible to fix, or at least not with the official AndroidX biometric library that I'm using in the app. The library does not let the application choose the type of biometrics and instead leaves the choice up to the device / manufacturer. So as long as your device has facial recognitation enabled, the library may use it when biometric authentication is requested the an app.

**Comment by Waboodoo** [comment] 2024-04-14 18:21
With version 3.11.0 I made a small adjustment to the biometric confirmation. It's tricky to test though, as the behavior differs between devices, but it should now favor using the fingerprint over facial recognition, which might solve the issue here.

**Comment by Waboodoo** [comment] 2024-05-05 16:57
Closing this now under the assumption that the issue is fixed or no longer relevant.

**Closed as completed by Waboodoo** 2024-05-05 16:57 UTC
Labels: bug
