### ISSUE TITLE
[BUG] URL() cannot be used?

### ISSUE THREAD

**Issue by braboobssiere** [Waboodoo/HTTP-Shortcuts#402] opened 2024-01-05 14:19 UTC
### Steps To Reproduce
i try to extract hostname from input url, using the following script:

```
const InputUrl = prompt("insert a url");
// let's use https://sub.example.com/catordog for testing

const Domain = new URL(InputUrl).hostname;

showDialog(Domain, "result");
```

### Expected behavior
i should get Dialog "sub.example.com"

### Actual behavior
i got URL is not define 

### Screenshots
https://pixeldrain.com/api/file/ea1VP9hX

### Context
Please complete the following information:
- Android OS Version: [11]
- App Version [3.9.0]
- ref: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by Waboodoo** [comment] 2024-01-07 08:17
That is an interesting find. All the Javascript capabilities are provided by a third-party library, so I don't have much control over what is available there. I'm surprised that `URL` doesn't seem to be supported at all. However, I don't think I can easily fix this. At the current time, with the Scripting feature I can't give any guarantees on which JS functionality is available and which is not, except of course for the functionality specifically declared by the app.

**Comment by Waboodoo** [comment] 2024-01-07 09:12
There is no such logic in the app. In Scripting, the app's variables can only be accessed via the `getVariable` and `setVariable` function.

**Comment by braboobssiere** [comment] 2024-01-07 09:26
right, i misunderstanding

**Comment by Waboodoo** [comment] 2024-05-19 17:52
Closing this now as it's technically not a bug but a lack of features in the underlying JS engine that I'm using. I have currently no way to fix this, but since it was not raised as an issue by anyone else I don't see it as a high priority. I'll keep an eye open for alternatives or improvements for the JS engine, but until then, the functionality available in the Scripting feature will be limited to what is supported by the current engine.

**Closed as completed by Waboodoo** 2024-05-19 17:52 UTC
Labels: bug
