### ISSUE TITLE
[BUG] Quick Settings Tile not working

### ISSUE THREAD

**Issue by femto-code** [Waboodoo/HTTP-Shortcuts#211] opened 2021-01-11 15:48 UTC
Thanks to the developer for this great app!

**Steps To Reproduce**
1. Go to shortcut and enable launch via quick settins tile in misc settings -> save shortcut.
2. Pull down drawer, and click on the shortcut used by HTTP Request Shortcuts

**Expected behavior**
Window/Modal asking to run a shortcut that was chosen/enabled to be launched via quick settings tile.

**Actual behavior**
Nothing happens, no reaction on click.

**System**
 - Android OS Version: 10
 - App Version 1.39.0 [latest currently]
 - might be also relevant: issue also persists when app is opened (in foreground and/or background)

Thank you in advance!

**Comment by Waboodoo** [comment] 2021-01-22 12:33
Thanks for the bug report. Unfortunately, I am not able to reproduce this issue, neither on a physical device nor in the emulator.

**Comment by femto-code** [comment] 2021-01-22 12:46
Thanks for your answer. Do you need any further information?

**Comment by Waboodoo** [comment] 2021-01-22 14:47
I'm not sure how to debug this, but maybe a start:
- What is the vendor of your device / Android?
- Do you use a custom launcher?

Otherwise, all I can suggest for now is to try and change battery saver or data saver modes, or to remove and re-add the quick settings tile.

**Comment by femto-code** [comment] 2021-01-26 22:33
- vendor of the device is Samsung
- Android is official custom ROM LineageOS 17.1 (Android 10)
- important: no Google Play Services (at all) on the device
- no custom launcher (default is Trebuchet)

I tried battery saver options for your app and (re-)adding quick settings tile but with no effect.

Thank you for your efforts!

**Comment by femto-code** [comment] 2021-06-07 20:03
Meanwhile I updated to Android 11 (again no Google Services at all) but the quick settings tile is still not working...
I assume there is somewhat like an incompatibility with the (default) launcher Trebuchet. Does anyone know of a solution or confirm this experience?
The quick tile feature would be very nice for me to use.

**Comment by Waboodoo** [comment] 2021-06-08 17:22
@femto-code What happens when you disable the quick settings tile option for all your shortcut and then click the quick settings tile?
It should show you a dialog window with instructions. I'd be curious to know whether that part works, it might help with pin-pointing the problem.

**Comment by femto-code** [comment] 2021-06-20 20:51
@Waboodoo Thanks for your instructions. This is very intersting: when I disable quick settings tile options for all shortcuts and then tap on the quick settings tile it is showing the dialog window that you described.
I hope that will help troubleshooting the issue, thanks in advance!

**Comment by Waboodoo** [comment] 2021-06-21 17:24
Thanks for checking. That at least narrows the problem space down a bit.

**Comment by t-animal** [comment] 2021-06-22 21:10
I can confirm this bug exists. In my case, if I have 2 shortcuts enabled for the quick settings tile I get a prompt asking me which shortcut to execute. If I have three shortcuts with that setting, it shows the described behavior.

**Comment by Waboodoo** [comment] 2021-07-23 18:39
I have identified and fixed a bug related to the Quick Settings Tile feature. It may not be the same issue as this one, but it might be related. It is part of the 2.6.0 release.
If you still encounter problems, there is also an additional troubleshooting option (you'll find it in the app's Settings) that you can try: "Allow Displaying Over Other Apps". Enabling it might fix the problem.

**Comment by t-animal** [comment] 2021-07-25 19:17
I've got a new phone, which came with a newer android version, too, so I can't say if it is fixed on my old phone. But on my new phone the quick settings tile works (again?) with three options. Unfortunately since google decided 6 quick settings tiles is enough per page, I hardly use it and mostly go via the app icon shortcuts now.

**Comment by Waboodoo** [comment] 2021-07-26 11:52
Cool. I will assume that this issue is then somewhat fixed and will close it. Feel free to comment if there's still a problem.

**Closed by Waboodoo** 2021-07-26 11:52 UTC
Labels: bug
