### ISSUE TITLE
Multiple delayed requests not send

### ISSUE THREAD

**Issue by pawalther** [Waboodoo/HTTP-Shortcuts#115] opened 2019-01-14 09:08 UTC
Delaying multiple request for the same shortcut does not work properly.

Scenario:
Without internet connection several request for one shortcut were issued (with different values for a single variable). Upon connection to the internet only the first request was sent to the API endpoint. All other requests did not reach the endpoint.

**Comment by Waboodoo** [comment] 2019-01-20 10:34
As of now, this is intended behavior. A shortcut can only be queued for delayed execution once at a time.
I can see however that this is a limitation, and I'll look into changing this so that multiple executions can be queued.

**Comment by Waboodoo** [comment] 2020-05-28 13:40
This will be fixed in the upcoming version 1.32.0.

**Comment by Waboodoo** [comment] 2020-06-14 15:09
Closing this now as 1.32.0 was release and this issue should be fixed. Please let me know if you still encounter problem.

**Closed by Waboodoo** 2020-06-14 15:09 UTC
