### ISSUE TITLE
app control on Android TV

### ISSUE THREAD

**Issue by pho084** [Waboodoo/HTTP-Shortcuts#399] opened 2024-01-02 16:01 UTC
hi

on AndroidTV systems (e.g. FireTV here) the app's "confirmation" controls for submitting , navigating menus etc do not work reliably.

e.g. when a dialogue box pops up and you enter text you cannot confirm the changes w the device's remote 

would be great if that was possible. and thank you kindly for this awesome application

**Comment by Waboodoo** [comment] 2024-01-07 08:23
You say "do not work reliably", does that mean there are places or times where it does work as expected? If so, could you give some examples? That would make it easier to fix this.

**Comment by pho084** [comment] 2024-01-07 13:08
thank you for your reply! 
where i have encountered it:
1) pretty much any dialogue box where you need to enter text. you just cannot click the confirm button (i mean you can but nothing happens)

2) (especially aggravating): when you try to import a shortcut and select "from file" or whatever it is called. Then the file manager pops up but you are stuck in "recently added" directory and can not change it because you cannot navigate to the side panel where the option is to change directories (i had to set up a local web server to import shortcuts^^)

thank you again for looking into this

**Comment by Waboodoo** [comment] 2024-02-09 09:12
Thanks for the details. Your second point is an odd one, because the file manager is not part of the app, but of the OS. I have no control over how it behaves. If a system component is broken like that, there might be an underlying issue with your device or its OS. I'm concerned that even if I find out how to improve the app's behavior, it might still not work well on your particular device.

**Comment by Waboodoo** [comment] 2024-05-19 17:55
Closing this now as I can not reproduce the issue and it might be outside the app's control. If anyone has more inputs, let me know and I can reopen it.

**Closed as completed by Waboodoo** 2024-05-19 17:55 UTC
Labels: bug
